### ISSUE TITLE
Deploy REANA with Kueue on GKE

### ISSUE THREAD

**Issue by xaviertintin** [xaviertintin/Thesis#15]
Seamlessly deploy REANA with Kueue on GKE

**Comment by xaviertintin** [comment]
Altered REANA helm values to replace the 2 official REANA Component images to images from my dockerhub. Check the commit [here](https://github.com/reanahub/reana/commit/1618df0d68e4a627db38cf66db692e8239d0f002).

**Comment by xaviertintin** [comment]
# REANA Deployment Guide

After creating your K8s Cluster in GKE follow the following steps:

## 1. Install Helm

Install Helm by running the following commands:

```
curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
chmod 700 get_helm.sh
./get_helm.sh
```

Create alias

```
echo "alias k='kubectl'" >> ~/.bashrc
source ~/.bashrc
k version
```

## 2. Set shared storage

Follow these steps to enable Filestore:

![Image](https://github.com/xaviertintin/Thesis/assets/79267255/6ca3a448-a621-43cd-b911-f257e5b2b8ad)

Create a Filestore instance as shown below:

![Image](https://github.com/xaviertintin/Thesis/assets/79267255/f0761d07-3455-42c2-bf0d-4d60e99bd98b)

![Image](https://github.com/xaviertintin/Thesis/assets/79267255/e1140201-fbf1-4890-ab46-281ed81e1375)


### 3. Create and Apply Persistent Volume (PV)

Create a pv.yaml file with the following content:

```
# pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: reana-shared-persistent-volume-storage
spec:
  storageClassName: reana-shared-volume-storage-class
  capacity:
    storage: 200Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /reana
    server: 10.186.208.130 #change according to your filestore server address
```

Apply the configuration using:

```
k apply -f pv.yaml
```


## 4. Deploy REANA with NFS in values

### - REANA Classic

Add REANA chart repository:

```
helm repo add reanahub https://reanahub.github.io/reana
helm repo update
```

Deploy REANA (note that you can pass any of the [supported values](https://github.com/reanahub/reana/blob/master/helm/reana/README.md)):

```
# extra.yaml 
shared_storage:
  backend: nfs  # hostpath | cephfs | nfs
  volume_size: 200
  access_modes: ReadWriteMany
node_label_infrastructure: reana.io/system=infrastructure
node_label_runtimebatch: reana.io/system=runtimebatch
node_label_runtimejobs: reana.io/system=runtimejobs
```

Deploy REANA with Helm:

```
helm install --devel reana reanahub/reana -f values.yaml
```
	
### - REANA with Kueue

Clone the REANA repository and deploy locally:

```
rm -r reana
git clone https://github.com/xaviertintin/reana.git
cd ~/reana/helm/reana  
helm dependency build
helm install --devel reana . -f extra.yaml 
```
## 5. Extra configurations:

After a couple minutes, initialize the database:

```
kubectl -n default exec deployment/reana-server -c rest-api -- \
        ./scripts/create-database.sh
```

Create administrator user and corresponding access token:

```
mytoken=$(kubectl -n default exec deployment/reana-server -c rest-api -- \
          flask reana-admin create-admin-user --email john.doe@example.org \
                                              --password mysecretpassword)
```

Store administrator access token as Kubernetes secret:

```
kubectl -n default create secret generic reana-admin-access-token \
        --from-literal=ADMIN_ACCESS_TOKEN="$mytoken"
```

## 6. Create REANA Virtual Environment

`If` it's the first time, create a virtual environment and install the REANA client:

```
virtualenv ~/.virtualenvs/reana
source ~/.virtualenvs/reana/bin/activate
pip install --upgrade pip
pip install reana-client
```

`Else` if you already created it before, just activate it with:

```
source ~/.virtualenvs/reana/bin/activate
```

## 7. GKE configuration

WRT ingress, if you do `kubectl get services`, you should see `reana-traefik` with NodePort running on port 30443 on some machine. After that you should be able to open firewall access to port 30443 with something like:

```
gcloud compute firewall-rules create test-node-port --allow tcp:30443
```

Get all pods from your REANA deployment.
```
k get pods
```

Get more info on your REANA Traefik pod with:

```
kubectl get pod reana-traefik-xxxx-xxxx -o wide
```

Also, you should check "internal IP" vs "external IP" to the node, via something like:
```
gcloud compute instances list
```

This should list `EXTERNAL_IP` of the node where traefik runs, something like `23.251.141.219`. The REANA server should then be available at

```
https://23.251.141.219:30443
```

You should then export the respective credentials with something like:

```
export REANA_SERVER_URL=https://xx.xxx.x.xx:30443
export REANA_ACCESS_TOKEN=xxxxxxxxxxxxxxxxxx
```


## 8. Configure Kueue

Install Kueue and configure resources:

```
VERSION=v0.7.0
kubectl apply --server-side -f https://github.com/kubernetes-sigs/kueue/releases/download/$VERSION/manifests.yaml
```

If you want to use a specific node for the Kueue deployment, replace the gke-cluster-1-default-pool-14af76c5-0wzg with your own, and patch it with a similar command to:

```
kubectl patch deployment kueue-controller-manager -n kueue-system --type='json' -p='[{"op": "add", "path": "/spec/template/spec/nodeSelector", "value": {"kubernetes.io/hostname": "gke-cluster-1-default-pool-14af76c5-0wzg"}}]'
```

Calculate the resources for Kueue, the Kueue configuration file can look something like:

```
# Run Batch Job
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "cluster-queue-reana-run-batch"
spec:
  namespaceSelector: {} 
  cohort: "reana"
  resourceGroups:
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: "default-flavor"
      resources:
        - name: "cpu"
          nominalQuota: 4000m
        - name: "memory"
          nominalQuota: 14305Mi
---
# Run Job
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "cluster-queue-reana-run-job"
spec:
  namespaceSelector: {} 
  cohort: "reana"
  resourceGroups:
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: "default-flavor"
      resources:
        - name: "cpu"
          nominalQuota: 8000m
        - name: "memory"
          nominalQuota: 28610Mi
---
# Run Batch Job
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: "default"
  name: "local-queue-batch"
spec:
  clusterQueue: "cluster-queue-reana-run-batch"
---
# Run Job
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: "default"
  name: "local-queue-job"
spec:
  clusterQueue: "cluster-queue-reana-run-job"
---
# default-flavor.yaml
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: "default-flavor"

```

Apply with:

```
k apply -f kueueArch.yaml
```

## 8. Run Test

Test connection

```
reana-client ping
```

Run a simple workflow

```
reana-client create -n Testing
export REANA_WORKON=Testing
reana-client upload
reana-client start
```

## 8. Clean up

```
helm uninstall reana
gcloud compute firewall-rules delete test-node-port
```
